export const ALL_SLIDER_REQUEST = "ALL_SLIDER_REQUEST"
export const ALL_SLIDER_SUCCESS = "ALL_SLIDER_SUCCESS"
export const ALL_SLIDER_FAIL = "ALL_SLIDER_FAIL"

export const SLIDER_DETAILS_REQUEST = "SLIDER_DETAILS_REQUEST"
export const SLIDER_DETAILS_SUCCESS = "SLIDER_DETAILS_SUCCESS"
export const SLIDER_DETAILS_FAIL =    "SLIDER_DETAILS_FAIL"

export const CLEAR_ERRORS ='CLEAR_ERRORS'